# Generated by Django 5.2 on 2025-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('vicerrector', 'Vicerrector')], default='user', max_length=20, verbose_name='role'),
        ),
    ]
