# Generated by Django 5.2 on 2025-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.CharField(max_length=50, verbose_name='Código del Curso')),
                ('semestre', models.CharField(max_length=50, verbose_name='Semestre')),
                ('nom_curso', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('jornada', models.CharField(max_length=20, verbose_name='Jornada')),
                ('grupo', models.CharField(max_length=20, verbose_name='Grupo')),
                ('programa', models.CharField(max_length=100, verbose_name='Programa')),
                ('cupo_max', models.IntegerField(verbose_name='Cupo Máximo')),
                ('no_estud', models.IntegerField(default=0, verbose_name='Número de Estudiantes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
